cekurte_zcpe:
    resource: "@CekurteZCPEBundle/Controller/"
    type:     annotation
    prefix:   /

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

# ------------------------------------------------------------------------------
# CekurteUploaderBundle

_imagine:
    resource:   "@LiipImagineBundle/Resources/config/routing.xml"
    options: { i18n: false }

oneup_uploader:
    resource:   .
    type:       uploader
    options: { i18n: false }

cekurte_uploader:
    resource:   "@CekurteUploaderBundle/Controller/"
    type:       annotation
    prefix:     /uploader/
    options: { i18n: false }

# ------------------------------------------------------------------------------
# FOSJsRoutingBundle

fos_js_routing:
    resource:   "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    options: { i18n: false }

# ------------------------------------------------------------------------------
# FOSUserBundle

cekurte_custom_user:
    resource:   "@CekurteCustomUserBundle/Resources/config/routing/fosuser.yml"
    prefix:     /admin/

fos_user_security:
    resource:   "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource:   "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:     /register

# ------------------------------------------------------------------------------
# OAuth

google_login:
    pattern:    /admin/connect/check-google

hwi_oauth_security:
    resource:   "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:     /admin/connect

hwi_oauth_connect:
    resource:   "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:     /admin/connect

hwi_oauth_redirect:
    resource:   "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:     /admin/connect