security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CONTRIBUTOR: ROLE_USER
        ROLE_ADMIN:       ROLE_CONTRIBUTOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        admin:
            pattern:                    ^/((admin|pt_BR/admin).)(.*)
            form_login:
                provider:               fos_userbundle
                csrf_provider:          form.csrf_provider
                default_target_path:    admin
                login_path:             admin_fos_user_security_login
                failure_path:           admin_fos_user_security_login
                check_path:             admin_fos_user_security_check
                use_forward:            false
            oauth:
                resource_owners:
                    google:             google_login
                default_target_path:    admin
                login_path:             admin_fos_user_security_login
                failure_path:           admin_fos_user_security_login
                check_path:             admin_fos_user_security_check
                oauth_user_provider:
                    service:            oauth_custom_user_provider
            logout:
                path:                   admin_fos_user_security_logout
                target:                 home
            anonymous:                  true

        api:
            pattern:                    ^/api
            http_basic:
                realm:                  "API Secured Area"
                provider:               fos_userbundle

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        # -> Admin URL's
        - { path: ^/admin/login$,             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pt_BR/admin/login$,       role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/logout$,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pt_BR/admin/logout$,      role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/login-check$,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pt_BR/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/connect,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pt_BR/admin/connect,      role: IS_AUTHENTICATED_ANONYMOUSLY }

        # -> end

        # -> Secured Area
        - { path: ^/api,                role: [ROLE_API] }

        - { path: ^/admin,              role: [ROLE_USER] }
        - { path: ^/pt_BR/admin,        role: [ROLE_USER] }
        # -> end
