security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        admin:
            pattern:                    ^/admin(.*)
            oauth:
                resource_owners:
                    google:             /admin/connect/check-google
                default_target_path:    /admin
                login_path:             /admin/login
                failure_path:           /admin/login
                check_path:             /admin/login/login_check
                oauth_user_provider:
                    service:            oauth_custom_user_provider
            logout:
                path:                   /admin/logout
                target:                 /admin/login
            anonymous:                  true





        main:
            pattern:                    ^/
            form_login:
                provider:               fos_userbundle
                csrf_provider:          form.csrf_provider
                default_target_path:    /area-do-usuario
                login_path:             fos_user_security_login
                failure_path:           fos_user_security_login
                check_path:             fos_user_security_check
                use_forward:            false
            oauth:
                resource_owners:
                    facebook:           /connect/check-facebook
                default_target_path:    /area-do-usuario
                login_path:             /login
                failure_path:           /login
                oauth_user_provider:
                    service:            oauth_custom_user_provider
            logout:
                path:                   /logout
                target:                 /
            anonymous:                  true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        # -> Admin URL's
        - { path: ^/admin/login$,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/connect/check-google$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        # -> User Profile URL's
        - { path: ^/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        # -> end

        # -> Secured Area
        - { path: ^/area-do-usuario,    role: [ROLE_USER] }
        - { path: ^/admin,              role: [ROLE_ADMIN] }
        # -> end
